# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 19:44
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='title', unique_with=('created_date',)),
            preserve_default=False,
        ),
    ]
